
## NUMPY EXERCISES:

In [2]:
import numpy as np 
import sys

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [14]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
#GETTING DIMENSIONS
a.ndim
b.ndim

2

In [13]:
#GETTING SHAPES:
b.shape

(2, 3)

In [17]:
#GETTING TYPE:
a.dtype

dtype('int32')

In [20]:
#GETTING SIZE:
a.itemsize

4

### Accesing/Changing specific elements, rows, columns, etc

In [22]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [28]:
# get a specific element [row,columns]
a[1,5]

13

In [29]:
#get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
#get a specific column
a[:,2]

array([ 3, 10])

In [31]:
# [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

### Initializing different types of Arrays

In [33]:
#all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# all 1s matric 
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [35]:
# any other number 
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [38]:
# Any number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [39]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.6768683 , 0.5974867 ],
       [0.0176176 , 0.92469302],
       [0.76769158, 0.19647314],
       [0.27956243, 0.7078677 ]])

In [41]:
np.random.random_sample(a.shape)

array([[0.68397437, 0.19755263, 0.05773805, 0.7219367 , 0.54091771,
        0.13648928, 0.50360737],
       [0.93836056, 0.11235376, 0.73760208, 0.69381159, 0.33584396,
        0.88562167, 0.79970897]])

In [47]:
# random INT 
np.random.randint(-2,7,size=(3,3))

array([[ 1,  5,  4],
       [-1,  3,  4],
       [ 0,  6,  6]])

In [48]:
# the identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
# repeat an array
arr = np.array([[1,2,3]])
r1= np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [61]:
output = np.ones((5,5))
print(output)


z= np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Copying arrays

In [68]:
a = np.array([1,2,3])
b=a.copy()
b[0]=100
b


array([100,   2,   3])

### Math

In [69]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


a +2

In [71]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [72]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [73]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [77]:
# sin()

np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear

In [81]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [83]:
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [84]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
np.min(stats, axis=1)

array([1, 4])

In [86]:
np.max(stats)

6

In [87]:
np.sum(stats)

21

### Reorganizing Arrays

In [93]:
before = np.array([[1,2,3,4],[4,5,6,7]])
print(before)


after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [4 5 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


### Vertically stacking vectors

In [97]:

v1 =np.array([1,2,3,4])
v2 =np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [103]:
# Horizontal stack 
h1 = np.ones((2,4))
h2 = np.ones((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])